
device: "cuda:0"
random_seed : 1

data_conf: 
  dataset: "mnist"
  dimension: 784
  random_state: 0
  data_path: "../../datapath/"
  val_fraction: 0.3
  flatten: False
  
model_conf:
  model_name: "lenet"
  #input_dimension: 784
  #model_name: 'lenet'
  num_classes: 10
  fit_intercept: True
  lib: "pytorch"

training_conf: 
  optimizer: "sgd"
  learning_rate: 0.1
  loss_tolerance: 1e-6
  max_epochs: 20
  normalize_weights: False
  batch_size: 128
  log_batch_loss_freq: 100
  
  #stopping_criterion: "val_err_threshold"
  #val_err_threshold: 0.05
  ckpt_load_path: null    

inference_conf:
  shuffle: False
  batch_size: 512


output:
  log_file_path: '${base_dir}/outputs/logs/temp.log'


